### ISSUE TITLE
Performances: Replace Socket.io/ws/express with uwebsockets.js

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1750]
According latest perf tests, socket.io does not scale

**Comment by LucasBrazi06** [comment]
https://alexhultman.medium.com/moving-from-socket-io-to-%C2%B5websockets-js-a85753b93a5a

**Comment by jerome-benoit** [comment]
https://github.com/uNetworking/uWebSockets.js scale because: 
+ the core code is written in C/C++;
+ it does not rely on external server code. 

That means that it can't integrated inside the existing express HTTP server used by the REST API on a route. It can be only used as a standalone server listening on another port. On SCP that means another application. 
Since it looks like way more efficient and featured than ws, a complete switch to its usage everywhere should also solve scalability issue on OCPP-J service. The ws code is encapsulated in two files: WSServer.ts and WSClient.ts, so it should not be too long to migrate, even with the API change on event handling.  
It can also totally replace express.

**Comment by jerome-benoit** [comment]
+ express: 
	+ REST API: too much features are lost: integrated security, parser, etc. middleware and it's not a performance bottleneck for now. Endpoint callbacks need some rewriting. 
	+ socket.io: need to be split out the REST express HTTP to its own app (SCP) or port. Make sense performance wise if we plan to use also the embedded publisher/subscriber API as a message passing system for the charging stations remote commands handling.
+ ws: 
    + OCPP-J: the performance improvements worth the small rewrite on a component that really needs to scale.
