### ISSUE TITLE
Templates: Handle mono and tri phased charging stations

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#1880]
Tri phased AC charging stations can always be wired mono phased. 
The number of phases shall be something like: `[1, 3]` instead of `1` or `3` and the tenant admin or operator can set that value depending on how it has been wired. 
Using amperage per phase in the template will ease that kind of use case. 
All calculation shall be consolidated in helper routines and all the routines shall use the number of phase and used everywhere. 

In progress design and rationale: https://wiki.piment-noir.org/doku.php/en:cs:modelling_multi-phased_electrical_system_interconnexion

**Comment by LucasBrazi06** [comment]
No revert on the topic of nb amps per phase until we discuss it. Meeting is scheduled already.

**Comment by jerome-benoit** [comment]
> No revert on the topic of nb amps per phase until we discuss it. Meeting is scheduled already.

I give you one code snippet that will not work out of box for 2 phased cars because of the total amperage in charging station template for 3 phases: 

   ```
      minCurrent: threePhasesCar ? (StaticLimitAmps.MIN_LIMIT_PER_PHASE * numberOfPhases) : 
      StaticLimitAmps.MIN_LIMIT_PER_PHASE,
      minCurrentPerPhase: StaticLimitAmps.MIN_LIMIT_PER_PHASE,
      maxCurrent: threePhasesCar ? maxConnectorAmps : (maxConnectorAmps / numberOfPhases), // Charge capability in Amps
      maxCurrentPerPhase: maxConnectorAmps / numberOfPhases, // Charge capability in Amps per phase
```

To support 2 phases cars, you just need make the boolean threePhasesCar more like a multiPhasesCar  detection boolean and the rest is working just perfectly for the minCurrent or minCurrentPerPhase calculation without any code changes. 
But for maxCurrent and maxCurrentPerPhase, because of the division by the 2, it's not gonna work like a charm without rounding ;)

We will discuss it again during the scheduled meeting after holidays for sure, but honestly that single example is really the shouting example that explains why everybody is using amp per phase to model multi-phased electrical system :) 

My last 2 euros before being away from computers for 3 weeks. 

Enjoy ;)

**Comment by LucasBrazi06** [comment]
You cannot work with 1 or two 2 phases because in the end the charging plan will be pushed per phase which I think is wrong so the standard is not right in that case!
Amps limit in the charging plan should be specified for each phase!
So whatever the Amps is 1 or 2 phases for the car, in the end the 3 phases will be limited even if only 1 or 2 is used and the energy of the other phases will not be redistributed to the other cars so this code above leads to no optimization in the end.
Digest me that ;-)

**Comment by LucasBrazi06** [comment]
I like the human approach because it is more natural for me and intuitive, we always state naturally the full power: this 
charging station is delivering 150kW and not 50kW per phase!
When I read the charging plan in the logs I have the same approach, full amps and I simply deduce the power in a second and check if it's right, I don't have to search the number of phase in the charging station conf (which is not provided in the charging plan) + do the multiplication and got the result after a minute!
That's the main difference between your approach and mine.
But again, each of them is right and can be discussed.

**Comment by LucasBrazi06** [comment]
As discussed make me a proposal/impact/time of refactoring with the user friendly approach we discussed (can be understandable by a human being in UI/Logs like Watts)
