### ISSUE TITLE
Car Management enhancements/bugs

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1973]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/dabc037d-8a4c-40e6-a663-f02aedfd4ee0)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/ba219e08-7f81-4323-a453-ce6624f75ebe)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7bb84790-470d-4b1f-8b52-31cc904fcc7c)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/6a1e519d-100a-4c2e-9ce3-f314b14f24cb)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/6484ddb1-d20e-44e2-8eff-4bbadec52950)

**Comment by stefania-santimbrean** [comment]
Testing notes:

- **Car seems to be present in Session View on the right but is empty (might be because no data in test?)**
- Rename to "Car Management" okay
- User displayed in Car Management List
- **in Edit Car, if I add a new user, Default Car and Car Owner are not selected. Should they be?**
- Badges text appears
