### ISSUE TITLE
Charging Station / Template: Override Template and provide manual settings on charging station

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2005]
Provide a checkbox to override the settings provided by the templates: Enable manual configuration
Once checked:
- Warning pop-up: The Charging Station will be setup manually and will reboot once saved
- Save:
  - All the charging station's connectors props will be set from the template
  - Charge points will be deleted from the model + Save in DB
  - Charging Station will be rebooted
  - Template will not be applied if this flag is set
- User can change the charging station manually

**Comment by LucasBrazi06** [comment]
@OliveGerste Let me know if you can manage to finish this one?

**Comment by OliveGerste** [comment]
@LucasBrazi06 This is what has been implemented since the last review:
- Charging stations are completely excluded from every template if manual configuration is enabled
- Charge Points are saved in the backend if manual configuration is enabled
- Charge Points are checked if the amperage, power, type and number of phases are correct
- The Front end sends charge points to the backend if manual configuration is enabled

There are still some bugs and additional testing for all kind of stations will be needed.  
So there is still some time, which needs to be invested on this task

**Comment by LucasBrazi06** [comment]
Ok, take the needed time now so we can close this issue which is greatly needed in prod.
Thanks!
