### ISSUE TITLE
RESTful / Schema : Migrate User service endpoint

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2275]
Start migrating 1 endpoint and make a PR. Next proceed with 3 by 3 + PR
- [x] Add User's REST service path in RESTful API
- [x] Add the new RESTful endpoints in the OAS file
- [x] Update the Unit Tests
- [x] Update the Front-end Http calls (make PR)
- [x] Update the Mobile App Http calls (after backend/front-end deployment in prod)
- [x] Update the Postman collection
- [x] Validate HTTP queries with JSon schemas in User service class (start with 1 endpoint and make a PR and next 3 by 3 + PR)
- [x] Remove User's security class
- [x] Remove User's old endpoint

@Ninjeneer 
Starts with GetUsers/GetUser/CreateUser/UpdateUser/DeleteUser in priority (customer's need)

**Comment by Ninjeneer** [comment]
@LucasBrazi06 @jerome-benoit Here is a proposal for the new user REST API. Is it suitable ?

Action | Old HTTP Method | Old route | New HTTP Method | New route
-- | -- | -- | -- | --
USER_CREATE | POST | /UserCreate | POST | /users
USERS | GET | /Users | GET | /users
USER | GET | /User | GET | /users/:id
USER_UPDATE | PUT | /UpdateUser | PUT | /users/:id
USER_DELETE | DELETE | /DeleteUser | DELETE | /users/:id
USER_DEFAULT_TAG_CAR | GET | /UserDefaultTagCar | GET | /users/:id/car-tag/default
USER_SITES | GET | /UserSites | GET | /users/:id/sites
ADD_SITES_TO_USER | POST | /AddSitesToUser | POST | /users/:id/sites
REMOVE_SITES_FROM_USER | POST | /RemoveSitesFromUser | DELETE | /users/:id/sites
USER_UPDATE_MOBILE_TOKEN | PUT | /UpdateUserMobileToken | PUT | /users/:id/mobile-token
USER_IMAGE | GET | /UserImage | GET | /users/:id/image
USERS_IN_ERROR | GET | /UsersInError | GET | /users/status/in-error
USERS_IMPORT | POST | /UsersImport | POST | /users/action/import
USERS_EXPORT | GET | /UsersExport | GET | /users/action/export

**Comment by LucasBrazi06** [comment]
Okay for me, just updated USER_DEFAULT_TAG_CAR.

**Comment by jerome-benoit** [comment]
> Okay for me, just updated USER_DEFAULT_TAG_CAR.

The initial proposal was more standard: <data>/<datasubsetfilter> and extensible: more custom filter could be added later on the same data without changing the root URI for that very same action.

**Comment by LucasBrazi06** [comment]
> The initial proposal was more standard: `<data>/<datasubsetfilter>` and extensible: more custom filter could be added later on the same data without changing the root URI for that very same action.

It was less understandable before my update.

**Comment by jerome-benoit** [comment]
> > The initial proposal was more standard: `<data>/<datasubsetfilter>` and extensible: more custom filter could be added later on the same data without changing the root URI for that very same action.
> 
> It was less understandable before my update.

By definition a REST endpoint scheme following a well known de facto standard is more understandable than any not documented scheme not following it. 
Since a user can have several tags and several cars, building filters will be needed. To apply the `default` filter  on `cars-tags` mixed data, the standard endpoint to get it is `cars-tags/default`. 

But that endpoint is an ugly hack should not be under the users related endpoints, it should be under the cars related and tags related endpoints. The code basically return the default car and default tag for a user:

`tags/{user or account or ...}/:userid/default`
`cars/{user or account or ...}/:userid/default`

The proper endpoint to avoid to call to the REST API two times must be: 

`tags-cars/{user or account or ...}/:userid/default`

But it's totally fine to call a REST API on different endpoints dealing with unrelated data.

**Comment by Ninjeneer** [comment]
Users are now fully migrated

**Comment by LucasBrazi06** [comment]
> Users are now fully migrated

Perfect, thanks!
